version: "3.8"

services:
  msib-squad3-app:
    container_name: msib-squad3-app
    image: msib-squad3-app/app:latest
    ports:
      - "8003:8003"
    restart: on-failure

networks:
  default:
    external:
      name: mysql_default
